### ISSUE TITLE
Can't get it installed

### ISSUE THREAD

**Issue by Dubidubiduu** [ryck/MMM-DHT-Sensor#22]
after npm install I get:

```
An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at /home/zz/MagicMirror/modules/MMM-DHT-Sensor/MMM-DHT-Sensor/node_modules/electron-rebuild/lib/src/cli.js:87:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/zz/MagicMirror/modules/MMM-DHT-Sensor/MMM-DHT-Sensor/node_modules/electron-rebuild/lib/src/cli.js:6:58)

```

**Comment by gh05tdog** [comment]
I sadly got the same, did you figure it out?

**Comment by ryck** [comment]
I can not replicate the issue... have you tried with the latest version?
